--- 
baseurl: /
collections: 
  category: 
    output: true
    permalink: "/category/:path/"
    title: Category
  posts: 
    output: true
    title: Posts
  uploads: 
    output: true
    title: Uploads
email: sherlifelix@gmail.com
exclude: 
  - Gemfile
  - Gemfile.lock
  - README.md
  - bin
  - vendor
  - _assets
  - node_modules
highlighter: rouge
include: 
  - _pages
kramdown: 
  auto_ids: true
  input: GFM
  syntax_highlighter: rouge
markdown: kramdown
paginate: 10
paginate_path: "/page:num/"
plugins: 
  - jekyll-sitemap
  - jekyll-paginate
prose: 
  media: assets/img
  metadata: 
    _posts: 
      - 
        field: 
          element: textarea
          label: Description
          placeholder: "Enter a Description"
        name: description
      - 
        field: 
          element: text
          label: Title
          value: "An awesome Headline!"
        name: title
      - 
        field: 
          element: hidden
          label: Layout
          value: blog_detail
        name: layout
      - 
        field: 
          element: hidden
          label: MetaTitle
          value: blog_title
        name: metatitle
      - 
        field: 
          element: text
          label: "SEO Keywords"
          value: ""
        name: keywords
      - 
        field: 
          element: text
          label: Category
          value: ""
        name: blog_category
      - 
        field: 
          element: text
          label: "Blog Image"
          value: /assets/img/animation.png
        name: thumbnail
      - 
        field: 
          element: textarea
          label: "Blog Highlight"
          value: ""
        name: blog_highlight
      - 
        field: 
          element: hidden
          label: Date
          value: CURRENT_DATETIME
        name: date
      - 
        field: 
          element: select
          label: "Author name"
          options: 
            - 
              name: Thomas
              value: Thomas
            - 
              name: Sherli
              value: Sherli
            - 
              name: Nancy
              value: Nancy
          value: "true"
        name: author_name
repository: sherlifelix.github.io/blog
sass: 
  style: compressed
timezone: UTC
title: "To Know Is Good"
