title: blog
email: sherlifelix@gmail.com
repository: sherlifelix.github.io/blog
timezone: UTC
baseurl: /
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - bin
  - vendor
  - _assets
  - node_modules
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
sass:
  style: compressed
include:
  - _pages
prose:
  media: assets/img
  metadata:
    _posts:
      - name: 'description'
        field:
          label: 'Description'
          element: 'textarea'
          placeholder: 'Enter a Description'
      - name: 'title'
        field:
          label: 'Title'
          element: 'text'
          value: 'An awesome Headline!'
      - name: 'layout'
        field:
          label: 'Layout'
          element: 'hidden'
          value: 'blog_detail'
      - name: 'keywords'
        field:
          label: 'SEO Keywords'
          element: 'text'
          value: ''
      - name: 'blog_category'
        field:
          label: 'Category'
          element: 'text'
          value: ''
      - name: 'thumbnail'
        field:
          label: 'Blog Image'
          element: 'text'
          value: '/assets/img/animation.png'
      - name: 'blog_highlight'
        field:
          label: 'Blog Highlight'
          element: 'textarea'
          value: ''
      - name: 'date'
        field:
          label: 'Date'
          element: 'hidden'
          value: 'CURRENT_DATETIME'
      - name: 'author_name'
        field:
          label: 'Author name'
          element: 'select'
          value: 'true'
          options:
            - name: 'sachin'
              value: 'sachin'
            - name: 'kholi'
              value: 'kholi'
            - name: 'dhoni'
              value: 'dhoni'
